### PR TITLE
Add certificate issuer parsing

### PR DESCRIPTION
**Pull request by Synse**
This adds support for parsing the issuer of a certificate using the same code used to parse subjects today.

I also added a simple test to ensure the values are parsed correctly, and updated the docs.

### CODE REVIEW

**Comment by Fitblip** [comment]
Hey this is rad, thanks for the PR. It looks like there are some merge conflicts, would you mind reconciling them? I'd be happy to approve/merge once things are green again!

**Comment by Synse** [comment]
👋 hey @Fitblip the merge conflicts are resolved. I also updated the docs to include `emailAddress`/`signature_algorithm` and added a test for signature algorithm parsing.

Let me know if there are any other changes you'd like to see.

xref #6 #7

**Comment by Fitblip** [comment]
Perfect, this looks great. Thanks for the PR 🚀

**Comment by Fitblip** [comment]
Released as 1.3.0! https://hex.pm/packages/easy_ssl/1.3.0

**Pull request merged**
